### ISSUE TITLE
incorrect logic on zero CRC 

### ISSUE THREAD

**Issue by flooduk** [kochedykov/jlibmodbus#11]
if crc16 checksum is zero, exception thrown, but checksum is correct
logs: 
INFO: Frame sent: F70400000010E550
INFO: Frame recv: F70420FFE2FFF0030C008C008404C004CC043A0007000C013D000C00040A3400020016F816
INFO: Frame sent: F70400000010E550
INFO: Frame recv: F70420FFE2FFF0030E008B008404C004CC043A0007000C013D000C00040A3400020016AD3D
INFO: Frame sent: F70400000010E550
INFO: Frame recv: F70420FFE3FFF10315008B008304C004CC043A0007000C0142000C00040A34000200160000
com.invertor.modbus.exception.ModbusChecksumException: checksum error: received 0, calculated 0
	at com.invertor.modbus.net.stream.InputStreamRTU.frameCheck(InputStreamRTU.java:44)
	at com.invertor.modbus.net.transport.ModbusTransportSerial.read(ModbusTransportSerial.java:50)
	at com.invertor.modbus.net.transport.ModbusTransport.readMessage(ModbusTransport.java:60)
	at com.invertor.modbus.net.transport.ModbusTransport.readResponse(ModbusTransport.java:55)
	at com.invertor.modbus.ModbusMaster.readResponse(ModbusMaster.java:110)
	at com.invertor.modbus.ModbusMaster.processRequest(ModbusMaster.java:135)
	at com.invertor.modbus.ModbusMaster.readInputRegisters(ModbusMaster.java:208)

**Comment by kochedykov** [comment]
Fixed, thank you.
